### ISSUE TITLE
Feature to track manual grade items

### ISSUE THREAD

**Issue by Urpokarhu1** [jonof/moodle-block_completion_progress#110]
Hello,

I would like to see an feature where you can track manual grade items with completion progress-block, at the moment this isn't possible.

![manual1](https://github.com/jonof/moodle-block_completion_progress/assets/53904029/046cead2-2c73-4b24-adcd-2ad480909655)
![manual2](https://github.com/jonof/moodle-block_completion_progress/assets/53904029/0e52a33b-6cde-4b5e-935b-c1315b566130)

**Comment by jonof** [comment]
This won't happen. The block presents only activity/resource completion status as tracked by Moodle's native completion API with limited augmentation of that information for specific activity types. Inclusion of other non-completion-API entities such as Grade book grade items is beyond the scope.
