### ISSUE TITLE
Scaling issue with large classes with high concurrent users

### ISSUE THREAD

**Issue by brendanheywood** [jonof/moodle-block_completion_progress#32]
I'm debugging a scaling issue, the root cause appears to be contention with this query:

```
SELECT g.id, '' || i.itemmodule || '-' || i.iteminstance || '-' || g.userid as exclusion
FROM mdl_grade_grades g, mdl_grade_items i
WHERE i.courseid = $1
AND i.id = g.itemid
AND g.excluded <> 0
```

Which is queried via:

`block_completion_progress_exclusions($course->id);`

In 2 of the 3 places this function is called, we are only concerned with the current user, and not the whole class, so I am thinking of making a second optional argument:

`block_completion_progress_exclusions($course->id, $user->id);`

and if this is set it will do a smaller lookup. We are doing more profiling and should have a pr ready at some stage

**Comment by brendanheywood** [comment]
Just a FYI that we've done some focused load testing on this and we've gotten roughly 3.5x more concurrency out of this block with this patch. It depends on the #of students enrolled and other factors but it's a good win

**Comment by agrowe** [comment]
I'm also seeing high load from this one query. It is accounting for >20% of database load when viewing stats for the previous hour.
