### ISSUE TITLE
Quiz with manual grading not showing "submitted but not graded"

### ISSUE THREAD

**Issue by collinsconstruction** [jonof/moodle-block_completion_progress#45]
I have a quiz with essay questions.
The student submits the quiz.
The gradebook says "Not yet graded".

The Completion progress block shows the same colour and message for this quiz as one that hasn't been attempted.

The colour is blue, not yellow.  The message on hover is "Not completed".

This is a problem because it confuses students, where they see the quiz is not complete, open it, and discover that actually they have submitted, and it is waiting grading.

**Comment by Urpokarhu1** [comment]
i would like to see this fixed also @jonof

**Comment by jonof** [comment]
From the test I just did in Moodle 3.9, I'm pretty sure there's bigger problems with the completion status never updating for a student once their essay responses are graded. The (closed as duplicate) HQ issue [MDL-51220](https://tracker.moodle.org/browse/MDL-51220) still seems to be a problem from what I just experienced.

**Comment by Urpokarhu1** [comment]
Hello,

Could you make a new tracker issue at tracker.moodle.org for version 3.9? https://tracker.moodle.org/browse/MDL-58196 has been closed as fixed but it clearly isn't then

**Comment by jonof** [comment]
Maybe next year, after I find the interest in trying to fix the problem.

**Comment by Urpokarhu1** [comment]
Hello,

If you post the problem at Tracker you personally don't have to fix it if it's in Moodle core, someone else might do it.

**Comment by jonof** [comment]
I know how this usually works, because I've been working with Moodle a while: they say "thanks, please send a patch".

**Comment by Urpokarhu1** [comment]
True :) but if you post it now there is a slim change someone will pick it up someday even if it's you later

**Comment by Urpokarhu1** [comment]
But if you don't have time I will do it for you

**Comment by jonof** [comment]
Actually, I'm wrong. I was confused by the meaning of the "require passing grade" completion criteria. Moodle is seemingly working as frustratingly designed.

**Comment by Urpokarhu1** [comment]
Hello,

So does this mean you need to develop completion progress more so it would show submitted but not yet graded quiz a different color than for ungraded quiz?

**Comment by jonof** [comment]
The change referenced above isn't finished. It hasn't had tests written yet and I haven't figured out the full array of completion state versus cell colour possibilities. The point of this block is to show activity completion status according to Moodle's logic, but as these special-case overrides get introduced, it muddies things up. I'm not yet certain what I've written so far is actually correct.

**Comment by danahsm** [comment]
We would also like to see this fixed also @jonof.  Is there a way we can prioritise this? Thanks

**Comment by jonof** [comment]
Feel free to test the changes in the [submitted-pending-grading](https://github.com/jonof/moodle-block_completion_progress/tree/submitted-pending-grading) branch and provide feedback on whether it behaves as you expect it to in your particular scenarios.
