### ISSUE TITLE
Submission state when working with groupings is not correct

### ISSUE THREAD

**Issue by adpe** [jonof/moodle-block_completion_progress#46]
Hi @deraadt 

We've encountered following problem when working with groupings in assignments. The student which has submitted the work has the correct display, but the other students in the group has always the wrong. The same behavior is also when the group gets the grading.

Here two examples:
![image](https://user-images.githubusercontent.com/9467708/66142031-097e2e00-e605-11e9-8796-0de75dee3f00.png)

---

![image](https://user-images.githubusercontent.com/9467708/66141985-f8352180-e604-11e9-8488-e60e75b07cdb.png)

---

I was working already on a patch and it works with my first tests. The pull request will follow soon.

Greets,
Adrian

**Comment by adpe** [comment]
Thank you very much @jonof 

What about the PR https://github.com/jonof/moodle-block_completion_progress/pull/47?

Greets
Adrian

**Comment by jonof** [comment]
I'd say see how it compares with what I've implemented and work out whether there's still a gap.

**Comment by adpe** [comment]
Hi @jonof 

So our work was not merged or preserved? As I saw, there are not contributions in this repository from me in person. So I don't think our code has actually landed in this plugin.

**Comment by jonof** [comment]
Hi Adrian

I didn't use your implementation for a few reasons:
1. I'd taken a different direction with the renovation which meant your approach was incompatible.
2. It looks like you removed [the code that handled Workshop submissions](https://github.com/ffhs/moodle-block_completion_progress/commit/fd7ad4183f0d93b0cb37b02845a12f928055c882#diff-8f5ff72ef1cf59199cfc4bbf16f2475d09e448601242f0d2c51bb94bd4aa1395L131-L138).
3. I didn't want the overhead of creating many Assignment object instances with all the bulk and waste database queries that involves when it still appeared practical to do it all with one query.

So unless I've missed something subtle in what I implemented, there was nothing to merge or preserve from your branch.

Jonathon

**Comment by adpe** [comment]
Hi Jonathon

Okay I understand, thanks for your further explanations. We'll try out your new version.

In the meantime I've closed the issue and the pull request. If something should be, we'll reopen it.

Greets
Adrian
