### ISSUE TITLE
Fix up the moodle plugins directory git repo links and canonical git repo for this plugin

### ISSUE THREAD

**Issue by brendanheywood** [jonof/moodle-block_completion_progress#61]
The plugin dir links to this repo:

https://moodle.org/plugins/block_completion_progress

But it lists @jonof as the maintainer who has a different repo:

https://github.com/jonof/moodle-block_completion_progress

Can I please suggest that:

1) Change the link to point to @jonof 's repo

2) It would be much better that if @deraadt is no longer the lead maintainer then can this repo be properly transferred to @jonof 's github repo space (or a new organisation space?) rather than it being a github fork, because all the github issues and pull requests appear only in the deraadt canonical version. We just need to make sure any divergence is not lost in the transfer

This way we don't get pull requests like https://github.com/deraadt/moodle-block_completion_progress/pull/33 going to the wrong place and stalling for 18 months

**Comment by jonof** [comment]
I only agreed to adopt the plugin last Thursday, so Michael and I are still finishing the transition. I've already changed the Plugins database entry this morning to point at my repository, but formally adopting Michael's repository and taking ownership of the issues tied to it is still being sorted out.

**Comment by brendanheywood** [comment]
ah excellent, and sorry for my impatience :/

**Comment by jonof** [comment]
This is complete.
