### ISSUE TITLE
Progress bar missing colors/styles

### ISSUE THREAD

**Issue by thebenkahn** [jonof/moodle-block_completion_progress#69]
Hello, on version 2020081000 the progress bars are not filling up correctly and I can see in the browser console that the associated CSS styles file *css.php* is not being found. I can verify the css.php file is present in the blocks/completion_progress directory. I can replicate this issue on both a 3.9.3 and a 3.10 test site.

The error is not present if I downgrade to 2020072900, all works as expected.

![progress-bar-blank](https://user-images.githubusercontent.com/30783598/108104566-528b2280-7040-11eb-810a-e25ab5f499a6.png)

![Snag_40da0ef](https://user-images.githubusercontent.com/30783598/108104868-b1e93280-7040-11eb-9e0a-941afeec09de.png)

**Comment by jazinheira** [comment]
@thebenkahn I was able to fix the issue by modifying css.php in PR #70!

**Comment by pavelsokolov** [comment]
It would be very nice to accept this PL to the master branch.

**Comment by jtsafran** [comment]
Agreed.   Would love to see this added to master!

**Comment by jonof** [comment]
PR #70 is now merged.
