### ISSUE TITLE
Problem with restore and groups

### ISSUE THREAD

**Issue by qkdgirl** [jonof/moodle-block_completion_progress#75]
Moodle 3.10. 4 - Plugin version 2021050400
when I do a full backup (with groups) a course that contains several completion progress block (each configured to be visible to a specific group), once I restore into a new course, only the first instance of a completion progress block restores, and it reconfigures to 'all participants'

**Comment by jonof** [comment]
What happens if you give each block instance a name such that no two are the same, and then backup-restore the course?

**Comment by jonof** [comment]
So I noticed the block doesn't presently make an effort to map across original group/grouping configuration to a different restored course, so I've begun adding that, however as to why the core 'Course copy' feature is dropping out block instances, I don't yet know, but I do know it's not the Completion Progress block doing that.

**Comment by qkdgirl** [comment]
> What happens if you give each block instance a name such that no two are the same, and then backup-restore the course?

That is the case in our course; every block has it's own name.
Thank you for adressing this so quickly.
