### ISSUE TITLE
timeout when sorting by progress

### ISSUE THREAD

**Issue by rimkov** [jonof/moodle-block_completion_progress#85]
hello
first of all thank you for this plugin :)
we installed it on our Moodle platform and integrated it into a course with 1300 students, however we encounter a timeout problem when we want to sort by progression. Is there another solution than to increase the different timeouts?

we are using Moodle 3.11.5+ and the plugin version 2021070900

thank you for your help.

**Comment by jonof** [comment]
Sorting by progress is by its nature an extremely expensive operation because there is no precomputed completion percentage stored anywhere in Moodle, so it has to be calculated on-demand for every participant.

**Comment by rimkov** [comment]
that's what we thought, thanks for your answer :)
