### ISSUE TITLE
Behavior of the “selected activities” configuration changed

### ISSUE THREAD

**Issue by melanietreitinger** [jonof/moodle-block_completion_progress#88]
Since the "[big sweeping code reorganisation](https://github.com/jonof/moodle-block_completion_progress/commit/fc8cc0a3482ecae6e9fc6bda92ffb213411602e2)", the behavior of the “selected activities” configuration changed: 

Before: when some activities had been selected for the block, it was possible to add more activities from the course on editing the block settings. 
Now the other, unselected activities are not shown any more. To see them I have to change "Activities included" to “All activities with completion set”, save and then change it again for “selected activities”. 

Is this inteded behaviour? And if so: why? 
As I see it, you can remove the lines 434-437 in `classes/completion_progress.php` completly.

**Comment by jonof** [comment]
> Is this inteded behaviour?
Nope, that's a mistake. Fix coming shortly.
